version: '3'
services:
  # Spring Boot Application
  spring-boot-app:
    image: rahmafeidi/srping:latest
    ports:
      - "9999:9999"
    networks:
      - app-network

  # Angular Application
  angular-app:
    image:  rahmafeidi/angular:latest
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
