version: '3'
services:
  # Spring Boot Application
  spring-boot-app:
    image: rahmafeidi/spring:latest
    ports:
      - "9999:9999"
    depends_on:
      - postgres-db
    networks:
      - app-network

  # Angular Application
  angular-app:
    image:  rahmafeidi/angular:latest
    ports:
      - "80:80"
    depends_on:
      - spring-boot-app
    networks:
      - app-network

  # PostgreSQL Database
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: useruser
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

